#!/usr/bin/env python3

import socket
import sys
import json

UNIX_SOCKET = "/var/run/btrfs-snabak.sock"


if __name__ == '__main__':
    try:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.connect(UNIX_SOCKET)
        argv_ser = json.dumps(sys.argv) + chr(0)
        sock.sendall(argv_ser.encode())

        # wait for the answer and print it
        reply = ''
        while True:
            b = sock.recv(1).decode()
            if b == "":
                break
            if b == chr(0):
                break
            reply += b

        sock.close()

        try:
            r = json.loads(reply)
            print(r["message"])
            code = r["exit_code"]

        except:
            print(f"could not parse daemon reply: '{reply}'")
            code = 255

        sys.exit(code)

    except FileNotFoundError:
        print(f"could not find '{UNIX_SOCKET}', is the daemon not running?")

    except ConnectionRefusedError:
        print("the socket is there but the daemon refuses to connect, did it crash?")

    except PermissionError:
        print(f"permission denied when trying to connect to socket '{UNIX_SOCKET}'")
